// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WBizTrip.API.Data;

#nullable disable

namespace WBizTrip.DataAccess.Migrations
{
    [DbContext(typeof(WBizTripDbContext))]
    [Migration("20220907071536_ChangeTripTable")]
    partial class ChangeTripTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WBizTrip.Domain.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("AnnualBudget")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TeamLeader")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hasdeu 1",
                            AnnualBudget = 10000f,
                            Name = "Universitatea Babes Bolyai",
                            PhoneNumber = "0711111111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Observatory street 1",
                            AnnualBudget = 10000.99f,
                            Name = "Universitatea Politehnica",
                            PhoneNumber = "0722222222"
                        });
                });

            modelBuilder.Entity("WBizTrip.Domain.Model.Intern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            Name = "Denisa Vamvu"
                        });
                });

            modelBuilder.Entity("WBizTrip.Domain.Model.TeamLeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TeamLeaders");
                });

            modelBuilder.Entity("WBizTrip.Domain.Model.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BusPassengers")
                        .HasColumnType("int");

                    b.Property<int>("CarPassengers")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightPassengers")
                        .HasColumnType("int");

                    b.Property<int>("LocalTransportType")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrainPassengers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("WBizTrip.Domain.Model.TripSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccommodationBudget")
                        .HasColumnType("int");

                    b.Property<string>("AccommodationInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodBudget")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransportBudget")
                        .HasColumnType("int");

                    b.Property<string>("TransportInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TripSuggestions");
                });

            modelBuilder.Entity("WBizTrip.Domain.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mircea.gabriel@gmail.com",
                            Name = "Gabriel Mircea",
                            Password = "passwordmircea",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "ivanmircea06@gmail.ro",
                            Name = "Mircea Ivan",
                            Password = "passwordivan",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "dmoga@yahoo.com",
                            Name = "Dani Moga",
                            Password = "passwordmoga",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "danielalupea1975@hotmail.com",
                            Name = "Daniela Lupea",
                            Password = "passwordlupea",
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            Email = "teamleader@hotmail.com",
                            Name = "testing",
                            Password = "passwordteamleader",
                            Role = 1
                        });
                });

            modelBuilder.Entity("WBizTrip.Domain.Model.TeamLeader", b =>
                {
                    b.HasOne("WBizTrip.Domain.Model.User", "User")
                        .WithOne("TeamLeader")
                        .HasForeignKey("WBizTrip.Domain.Model.TeamLeader", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WBizTrip.Domain.Model.Trip", b =>
                {
                    b.HasOne("WBizTrip.Domain.Model.Client", "Client")
                        .WithMany("Trips")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WBizTrip.Domain.Model.Client", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("WBizTrip.Domain.Model.User", b =>
                {
                    b.Navigation("TeamLeader");
                });
#pragma warning restore 612, 618
        }
    }
}
